# Generated by Django 3.0.3 on 2020-03-06 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeAnnounced', models.DateTimeField()),
                ('datetimeAdded', models.DateTimeField()),
                ('ageBracket', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('relatedPatients', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('label_ja', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('label_ja', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('label_ja', models.CharField(max_length=100)),
                ('source_id', models.IntegerField()),
                ('url', models.URLField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='detected_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_location_loc', to='patients.PatientLocation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientOrigin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='residing_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residing_location_loc', to='patients.PatientLocation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientStatus'),
        ),
    ]
