# Generated by Django 3.0.3 on 2020-03-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientorigin_label_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
