# Generated by Django 3.0.3 on 2020-03-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ageBracket',
            new_name='age_bracket',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='datetimeAdded',
            new_name='announced_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='datetimeAnnounced',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='relatedPatients',
            new_name='related_patients',
        ),
    ]
