# Generated by Django 3.0.3 on 2020-03-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200307_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlocation',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_bracket',
            field=models.IntegerField(blank=True, choices=[(None, ''), (0, '0-9'), (10, '10-19'), (20, '20-29'), (30, '30-39'), (40, '40-49'), (50, '50-59'), (60, '60-69'), (70, '70-79'), (80, '80-89'), (90, '90-99'), (100, '100+')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, ''), ('m', 'M'), ('f', 'F')], max_length=1, null=True),
        ),
    ]
