# Generated by Django 3.0.3 on 2020-03-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_patientlocation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('label_ja', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientsource',
            name='label',
        ),
        migrations.RemoveField(
            model_name='patientsource',
            name='label_ja',
        ),
        migrations.AddField(
            model_name='patientsource',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.DataSources'),
        ),
    ]
